#:kivy 1.11.0
#:import _ i18n._

ReviewScreen:
    name: 'Your Picture'

    BoxLayout:
        orientation: 'vertical'

        Image:
            id: photo

        AdaptiveBoxLayout:
            orientation: 'horizontal'
            size_hint_y: None

            KBButton:
                text: _("%s Print") % icon("print")
                
            KBButton:
                text: "%s Discard" % icon("trash")
